name: Build & Publish Docker images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gobitfly/eth2-beaconchain-explorer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}